// <auto-generated />
using ATMovie.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ATMovie.Migrations
{
    [DbContext(typeof(ATMovieContext))]
    [Migration("20231122101554_FirstPage")]
    partial class FirstPage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ATMovie.Models.Movie", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Runtime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieID");

                    b.ToTable("Movie");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            Description = "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
                            Genre = "Fantasy",
                            Price = 120,
                            Runtime = "120",
                            Title = "Lord of the Rings"
                        },
                        new
                        {
                            MovieID = 2,
                            Description = "Carol Danvers gets her powers entangled with those of Kamala Khan and Monica Rambeau, forcing them to work together to save the universe.",
                            Genre = "Fantasy",
                            Price = 120,
                            Runtime = "1h45m",
                            Title = "The Marvels"
                        },
                        new
                        {
                            MovieID = 3,
                            Description = "A dutiful damsel agrees to marry a handsome prince, only to find the royal family has recruited her as a sacrifice to repay an ancient debt. Thrown into a cave with a fire-breathing dragon, she must rely on her wits and will to survive.",
                            Genre = "Fantasy",
                            Price = 120,
                            Runtime = "1h25m",
                            Title = "Damsel"
                        },
                        new
                        {
                            MovieID = 4,
                            Description = "When a peaceful settlement on the edge of a distant moon finds itself threatened by the armies of a tyrannical ruling force, a mysterious stranger living among its villagers becomes their best hope for survival.",
                            Genre = "Fantasy",
                            Price = 120,
                            Runtime = "2h13m",
                            Title = "Rebel Moon - Part One: A Child of Fire"
                        },
                        new
                        {
                            MovieID = 5,
                            Description = "A charming thief and a band of unlikely adventurers embark on an epic quest to retrieve a lost relic, but things go dangerously awry when they run afoul of the wrong people.",
                            Genre = "Fantasy",
                            Price = 120,
                            Runtime = "2h14m",
                            Title = "Dungeons & Dragions: Honor among Thieves"
                        },
                        new
                        {
                            MovieID = 6,
                            Description = "Follow Riley, in her teenage years, encountering new emotions.",
                            Genre = "Animation",
                            Price = 120,
                            Runtime = "2h14m",
                            Title = "Inside out 2"
                        },
                        new
                        {
                            MovieID = 7,
                            Description = "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence. When the heroes clash on how to handle a new threat, Miles must redefine what it means to be a hero.",
                            Genre = "Animation",
                            Price = 120,
                            Runtime = "2h20m",
                            Title = "Spider-Man: Across the Spider-Verse"
                        },
                        new
                        {
                            MovieID = 8,
                            Description = "For the first time ever, Uta - the most beloved singer in the world - will reveal herself to the world at a live concert. The voice that the whole world has been waiting for is about to resound.",
                            Genre = "Animation",
                            Price = 120,
                            Runtime = "1h55m",
                            Title = "One Piece: Red"
                        },
                        new
                        {
                            MovieID = 9,
                            Description = "Garfield is about to go on a wild outdoor adventure. After an unexpected reunion with his long-lost father - the cat Vic - Garfield and Odie are forced to abandon their pampered life to join Vic in a hilarious, high-stakes heist.",
                            Genre = "Animation",
                            Price = 120,
                            Runtime = "2h05m",
                            Title = "Katten Gustaf: Filmen"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
